[versions]
compose = "1.10.1"
materialIconsExtended = "1.7.3"
agp = "8.12.3"
dateTimeVersion = "0.7.1"
kamelImageDefault = "1.0.9"
kotlin = "2.3.10"
koin = "4.1.1"
material3 = "1.9.0"
buildConfig = "6.0.9"
qrose = "1.1.2"
sqlDelight = "2.2.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.4"
androidx-lifecycle = "2.9.6"
androidx-navigation = "2.9.2"
composeHotReload = "1.0.0"
kotlinx-coroutines = "1.10.2"
ktor = "3.4.0"

[libraries]
# Compose
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
jetbrains-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

# KamelImage
kamel-image-default = { module = "media.kamel:kamel-image-default", version.ref = "kamelImageDefault" }

# Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Ktor
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Qrose
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }

# Supabase
supabase-storage-kt = { module = "io.github.jan-tennert.supabase:storage-kt" }
supabase-auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt" }
supabase-functions-kt = { module = "io.github.jan-tennert.supabase:functions-kt" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Kotlinx
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTimeVersion" }

# SQLDelight
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }

[plugins]
# Android - subject to change due to deprecation
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

# Compose
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Kotlin
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# SQLDelight
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }

# BuildConfig
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
